- hosts: all
  become: true
  remote_user: vagrant
  any_errors_fatal: true
  vars:
    distro: eloquent
    package: desktop
    shell: bash
  tasks:
  - name: Enable universe repository
    apt_repository:
      repo: "{{ item }}"
    loop:
      - "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
      - "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} {{ ansible_distribution_release }}-updates universe"
      - "deb http://security.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} {{ ansible_distribution_release }}-security universe"

  - name: Add ROS apt key
    apt_key:
      id: C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
      url: http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xC1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
      state: present

  - name: Add ROS repo
    apt_repository:
      repo: "{{ item }}"
    loop:
      - "deb http://packages.ros.org/ros2/ubuntu {{ ansible_distribution_release }} main"

  - name: Install packages
    apt:
      update_cache: true
      state: latest
      pkg: 
      - 'ros-{{ distro }}-{{ package }}'
      - python-rosdep

  - name: Setup environment
    lineinfile: 
      dest: '/home/{{ ansible_user }}/.{{ shell }}rc'
      regexp: '^source \/opt\/ros\/{{ distro }}\/setup.{{ shell }}'
      line: 'source /opt/ros/{{ distro }}/setup.{{ shell }}'

  - name: Initialize rosdep
    command: rosdep init
    args: 
      creates: /etc/ros/rosdep/sources.list.d/20-default.list

  - name: Update rosdep
    command: rosdep update
    become: false
    args:
      creates: '/home/{{ ansible_user }}/.ros/rosdep/sources.cache'
